---
- name: Windows server
  hosts: windows

  tasks:

  - name: Change Windows Registry 
    ansible.windows.win_regedit:
      path: {{ reg_key }}:{{ reg_path }}
      name: {{ reg_name }}
      data: {{ reg_data }}
      type: {{ reg_type }}
