---
- name: Windows server
  hosts: windows

  tasks:
  -  name :  Instala todas as atualizacoes de seguranca, criticas e rollup sem uma tarefa agenda
     win_updates : 
      category_names : 
        -  SecurityUpdates 
        -  CriticalUpdates 
        -  UpdateRollups

  -  name :  Instalar somente atualizacoes de seguranca como uma tarefa agendada para Server 212
     win_updates : 
      category_names :  SecurityUpdates 
      use_scheduled_task :  yes

  -  name :  somente pesquisa, retorna a lista de atualizacoes encontradas (se houver), faça login em C:\ansible_instala.txt
     win_updates : 
       category_names :  SecurityUpdates 
       state :  searched 

  -  name :  Instale todas as atualizacoes de seguranca
     win_updates : 
      category_names : 
      -  SecurityUpdates 
      reboot :  no

